export default [
  {
    id: 1,
    name: "India",
    capital: "New Delhi",
    region: "Asia",
    population: "1.45 Billion",
    flag: "https://flagcdn.com/w320/in.png",
  },
  {
    id: 2,
    name: "Germany",
    capital: "Berlin",
    region: "Europe",
    population: "84 Million",
    flag: "https://flagcdn.com/w320/de.png",
  },
  {
    id: 3,
    name: "Nigeria",
    capital: "Abuja",
    region: "Africa",
    population: "232 Million",
    flag: "https://flagcdn.com/w320/ng.png",
  },
  {
    id: 4,
    name: "Brazil",
    capital: "Brasília",
    region: "Americas",
    population: "212 Million",
    flag: "https://flagcdn.com/w320/br.png",
  },
  {
    id: 5,
    name: "Australia",
    capital: "Canberra",
    region: "Oceania",
    population: "27 Million",
    flag: "https://flagcdn.com/w320/au.png",
  },

  {
    id: 6,
    name: "Japan",
    capital: "Tokyo",
    region: "Asia",
    population: "123 Million",
    flag: "https://flagcdn.com/w320/jp.png",
  },
  {
    id: 7,
    name: "France",
    capital: "Paris",
    region: "Europe",
    population: "69 Million",
    flag: "https://flagcdn.com/w320/fr.png",
  },
  {
    id: 8,
    name: "Egypt",
    capital: "Cairo",
    region: "Africa",
    population: "118 Million",
    flag: "https://flagcdn.com/w320/eg.png",
  },
  {
    id: 9,
    name: "Canada",
    capital: "Ottawa",
    region: "Americas",
    population: "41 Million",
    flag: "https://flagcdn.com/w320/ca.png",
  },
  {
    id: 10,
    name: "New Zealand",
    capital: "Wellington",
    region: "Oceania",
    population: "5 Million",
    flag: "https://flagcdn.com/w320/nz.png",
  },

  {
    id: 11,
    name: "South Korea",
    capital: "Seoul",
    region: "Asia",
    population: "52 Million",
    flag: "https://flagcdn.com/w320/kr.png",
  },
  {
    id: 12,
    name: "Italy",
    capital: "Rome",
    region: "Europe",
    population: "59 Million",
    flag: "https://flagcdn.com/w320/it.png",
  },
  {
    id: 13,
    name: "South Africa",
    capital: "Pretoria",
    region: "Africa",
    population: "64 Million",
    flag: "https://flagcdn.com/w320/za.png",
  },
  {
    id: 14,
    name: "Argentina",
    capital: "Buenos Aires",
    region: "Americas",
    population: "47 Million",
    flag: "https://flagcdn.com/w320/ar.png",
  },
  {
    id: 15,
    name: "Fiji",
    capital: "Suva",
    region: "Oceania",
    population: "1 Million",
    flag: "https://flagcdn.com/w320/fj.png",
  },

  {
    id: 16,
    name: "Thailand",
    capital: "Bangkok",
    region: "Asia",
    population: "71 Million",
    flag: "https://flagcdn.com/w320/th.png",
  },
  {
    id: 17,
    name: "Spain",
    capital: "Madrid",
    region: "Europe",
    population: "49 Million",
    flag: "https://flagcdn.com/w320/es.png",
  },
  {
    id: 18,
    name: "Kenya",
    capital: "Nairobi",
    region: "Africa",
    population: "57 Million",
    flag: "https://flagcdn.com/w320/ke.png",
  },
  {
    id: 19,
    name: "Mexico",
    capital: "Mexico City",
    region: "Americas",
    population: "131 Million",
    flag: "https://flagcdn.com/w320/mx.png",
  },
  {
    id: 20,
    name: "Papua New Guinea",
    capital: "Port Moresby",
    region: "Oceania",
    population: "11 Million",
    flag: "https://flagcdn.com/w320/pg.png",
  },
  {
    id: 21,
    name: "Vietnam",
    capital: "Hanoi",
    region: "Asia",
    population: "101 Million",
    flag: "https://flagcdn.com/w320/vn.png",
  },
  {
    id: 22,
    name: "Netherlands",
    capital: "Amsterdam",
    region: "Europe",
    population: "18 Million",
    flag: "https://flagcdn.com/w320/nl.png",
  },
  {
    id: 23,
    name: "Morocco",
    capital: "Rabat",
    region: "Africa",
    population: "38 Million",
    flag: "https://flagcdn.com/w320/ma.png",
  },
  {
    id: 24,
    name: "Colombia",
    capital: "Bogotá",
    region: "Americas",
    population: "53 Million",
    flag: "https://flagcdn.com/w320/co.png",
  },
  {
    id: 25,
    name: "Samoa",
    capital: "Apia",
    region: "Oceania",
    population: "0.2 Million",
    flag: "https://flagcdn.com/w320/ws.png",
  },

  {
    id: 26,
    name: "Indonesia",
    capital: "Jakarta",
    region: "Asia",
    population: "285 Million",
    flag: "https://flagcdn.com/w320/id.png",
  },
  {
    id: 27,
    name: "Switzerland",
    capital: "Bern",
    region: "Europe",
    population: "9 Million",
    flag: "https://flagcdn.com/w320/ch.png",
  },
  {
    id: 28,
    name: "Ethiopia",
    capital: "Addis Ababa",
    region: "Africa",
    population: "135 Million",
    flag: "https://flagcdn.com/w320/et.png",
  },
  {
    id: 29,
    name: "Peru",
    capital: "Lima",
    region: "Americas",
    population: "35 Million",
    flag: "https://flagcdn.com/w320/pe.png",
  },
  {
    id: 30,
    name: "Papua New Guinea",
    capital: "Port Moresby",
    region: "Oceania",
    population: "11 Million",
    flag: "https://flagcdn.com/w320/pg.png",
  },

  {
    id: 31,
    name: "Pakistan",
    capital: "Islamabad",
    region: "Asia",
    population: "252 Million",
    flag: "https://flagcdn.com/w320/pk.png",
  },
  {
    id: 32,
    name: "Portugal",
    capital: "Lisbon",
    region: "Europe",
    population: "10 Million",
    flag: "https://flagcdn.com/w320/pt.png",
  },
  {
    id: 33,
    name: "Ghana",
    capital: "Accra",
    region: "Africa",
    population: "35 Million",
    flag: "https://flagcdn.com/w320/gh.png",
  },
  {
    id: 34,
    name: "Chile",
    capital: "Santiago",
    region: "Americas",
    population: "20 Million",
    flag: "https://flagcdn.com/w320/cl.png",
  },
  {
    id: 35,
    name: "Tonga",
    capital: "Nuku'alofa",
    region: "Oceania",
    population: "0.1 Million",
    flag: "https://flagcdn.com/w320/to.png",
  },

  {
    id: 36,
    name: "Malaysia",
    capital: "Kuala Lumpur",
    region: "Asia",
    population: "35 Million",
    flag: "https://flagcdn.com/w320/my.png",
  },
  {
    id: 37,
    name: "Sweden",
    capital: "Stockholm",
    region: "Europe",
    population: "11 Million",
    flag: "https://flagcdn.com/w320/se.png",
  },
  {
    id: 38,
    name: "Algeria",
    capital: "Algiers",
    region: "Africa",
    population: "46 Million",
    flag: "https://flagcdn.com/w320/dz.png",
  },
  {
    id: 39,
    name: "Cuba",
    capital: "Havana",
    region: "Americas",
    population: "11 Million",
    flag: "https://flagcdn.com/w320/cu.png",
  },
  {
    id: 40,
    name: "Vanuatu",
    capital: "Port Vila",
    region: "Oceania",
    population: "0.3 Million",
    flag: "https://flagcdn.com/w320/vu.png",
  },
  {
    id: 41,
    name: "Philippines",
    capital: "Manila",
    region: "Asia",
    population: "116 Million",
    flag: "https://flagcdn.com/w320/ph.png",
  },
  {
    id: 42,
    name: "Norway",
    capital: "Oslo",
    region: "Europe",
    population: "5.5 Million",
    flag: "https://flagcdn.com/w320/no.png",
  },
  {
    id: 43,
    name: "Tanzania",
    capital: "Dodoma",
    region: "Africa",
    population: "69 Million",
    flag: "https://flagcdn.com/w320/tz.png",
  },
  {
    id: 44,
    name: "Uruguay",
    capital: "Montevideo",
    region: "Americas",
    population: "3.5 Million",
    flag: "https://flagcdn.com/w320/uy.png",
  },
  {
    id: 45,
    name: "Solomon Islands",
    capital: "Honiara",
    region: "Oceania",
    population: "0.8 Million",
    flag: "https://flagcdn.com/w320/sb.png",
  },

  {
    id: 46,
    name: "Bangladesh",
    capital: "Dhaka",
    region: "Asia",
    population: "175 Million",
    flag: "https://flagcdn.com/w320/bd.png",
  },
  {
    id: 47,
    name: "Austria",
    capital: "Vienna",
    region: "Europe",
    population: "9 Million",
    flag: "https://flagcdn.com/w320/at.png",
  },
  {
    id: 48,
    name: "Uganda",
    capital: "Kampala",
    region: "Africa",
    population: "51 Million",
    flag: "https://flagcdn.com/w320/ug.png",
  },
  {
    id: 49,
    name: "Bolivia",
    capital: "Sucre",
    region: "Americas",
    population: "12 Million",
    flag: "https://flagcdn.com/w320/bo.png",
  },
  {
    id: 50,
    name: "Kiribati",
    capital: "South Tarawa",
    region: "Oceania",
    population: "0.13 Million",
    flag: "https://flagcdn.com/w320/ki.png",
  },

  {
    id: 51,
    name: "Singapore",
    capital: "Singapore",
    region: "Asia",
    population: "6 Million",
    flag: "https://flagcdn.com/w320/sg.png",
  },
  {
    id: 52,
    name: "Belgium",
    capital: "Brussels",
    region: "Europe",
    population: "12 Million",
    flag: "https://flagcdn.com/w320/be.png",
  },
  {
    id: 53,
    name: "Senegal",
    capital: "Dakar",
    region: "Africa",
    population: "18 Million",
    flag: "https://flagcdn.com/w320/sn.png",
  },
  {
    id: 54,
    name: "Ecuador",
    capital: "Quito",
    region: "Americas",
    population: "18 Million",
    flag: "https://flagcdn.com/w320/ec.png",
  },
  {
    id: 55,
    name: "Palau",
    capital: "Ngerulmud",
    region: "Oceania",
    population: "0.02 Million",
    flag: "https://flagcdn.com/w320/pw.png",
  },

  {
    id: 56,
    name: "Nepal",
    capital: "Kathmandu",
    region: "Asia",
    population: "31 Million",
    flag: "https://flagcdn.com/w320/np.png",
  },
  {
    id: 57,
    name: "Greece",
    capital: "Athens",
    region: "Europe",
    population: "10 Million",
    flag: "https://flagcdn.com/w320/gr.png",
  },
  {
    id: 58,
    name: "Cameroon",
    capital: "Yaoundé",
    region: "Africa",
    population: "29 Million",
    flag: "https://flagcdn.com/w320/cm.png",
  },
  {
    id: 59,
    name: "Costa Rica",
    capital: "San José",
    region: "Americas",
    population: "5 Million",
    flag: "https://flagcdn.com/w320/cr.png",
  },
  {
    id: 60,
    name: "Marshall Islands",
    capital: "Majuro",
    region: "Oceania",
    population: "0.04 Million",
    flag: "https://flagcdn.com/w320/mh.png",
  }

];